# Site
name: "thucdev"
title: "thucdev"
description: "A place to share my knowledge about technology and system design in the web development industry."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
ur: "https://thucdev.github.io"
baseurl: ""
google_analytics: "G-01CDELMFVJ"
disqus: "demowebsite"
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: thucdo.coder@gmail.com

# Authors
authors:
    william:
        name: William
        display_name: William
        avatar: "assets/images/avatar-sal.png"
        email: thucdo.coder@gmail.com
        web: https://www.linkedin.com/in/do-thuc-coder
        github: https://github.com/thucdev
        # twitter: https://twitter.com/wowthemesnet
        description: "With 3 years of experience in the field of web design, I am passionate about leveraging my diverse background to deliver exceptional results. Let's work together to bring your vision to life!"

# Plugins
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives
    - jekyll-figure

# Archives
jekyll-archives:
    enabled:
        - categories
    layout: archive
    permalinks:
        category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
    sass_dir: _sass
    style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
